# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${CI_BUILDS_DIR}/app/npm/

run tests:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - echo "Run tests here"
    - sleep 3
    - echo "SUCCESS"

deploy to production:
  stage: deploy
  only:
    - master
  variables:
    NODE_ENV: "production"
  script:
    - npm install -g netlify-cli
    - cd ./app
    - npm ci --cache ${CI_BUILDS_DIR}/app/npm --prefer-offline
    - npm run build
    - netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./build

