# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - test
  - deploy

cache:
  paths:
    - $HOME/.npm/cache

run tests:
  stage: test
  script:
    - echo "Run tests here"
    - sleep 3
    - echo "SUCCESS"

deploy to production:
  stage: deploy
  only:
    - master
  script:
    - npm install -g netlify-cli
    - cd ./app
    - npm ci
    - npm run build
    - netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./build

